
enc:
	gcc -Wall key.c encrypt.c -o encrypt

decrypt:
	gcc -Wall key.c hope.c tabelaSimbolos.c -o decrypt

brute:
	gcc -Wall key.c brute.c -o brute

clean:
	rm -f *.o a.out encrypt gmon.out prof brute
